/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeIndex {
  bulkBuild(items: Array<NativeItem>): Promise<unknown>
  search(vector: Float32Array, options: NativeSearchOptions): Promise<unknown>
  /**
   * Searches a pinned manifest snapshot instead of the latest published
   * state. Expired snapshots reject with `SNAPSHOT_EXPIRED`; snapshots
   * taken from a different index handle (including a previous open of the
   * same named index) reject with `INVALID_ARGUMENT` — segment numbering
   * could coincide across indexes and silently return wrong results.
   */
  searchWithSnapshot(vector: Float32Array, options: NativeSearchOptions, snapshot: NativeSnapshot): Promise<unknown>
  /**
   * Pins the currently published manifest snapshot. Cheap for both
   * providers (a clone of the in-memory manifest under a mutex; the file
   * provider caches its manifest), so it runs synchronously.
   */
  snapshot(): NativeSnapshot
  insert(item: NativeItem): Promise<unknown>
  delete(id: bigint): Promise<unknown>
  /**
   * Releases the native handle. Later calls on this instance fail with a
   * clear "index is closed" error, which the async wrapper surfaces as a
   * promise rejection. Named memory indexes stay registered (and can be
   * re-opened) after close; file-backed indexes release their directory
   * lock (once in-flight tasks finish) so the directory can be re-opened
   * or destroyed.
   */
  close(): void
}

/**
 * Opaque pinned manifest snapshot handle backing the JS `Snapshot` class.
 *
 * Holds a full [`ManifestSnapshot`] value (plain metadata, no storage
 * references), so its lifetime is simply the JS object's lifetime: it is
 * freed by garbage collection and needs no explicit release. Pinning a
 * snapshot does **not** prevent the memory provider from garbage-collecting
 * the hot-delta state it refers to: once more than one publish has elapsed
 * since the snapshot was taken, searches through it may reject with
 * `SNAPSHOT_EXPIRED`.
 */
export declare class NativeSnapshot {

}

/** Creates an index for a storage-provider URI (strict-create semantics). */
export declare function createIndex(uri: string, config: NativeIndexConfig): Promise<NativeIndex>

/**
 * Destroys an index by URI. For `memory:<name>` this removes the registry
 * entry (the escape hatch for the registry's process-lifetime retention);
 * for `file:` it deletes the index directory under the safety rules
 * documented on the module.
 */
export declare function destroyIndex(uri: string): Promise<void>

export interface NativeHit {
  id: bigint
  distance: number
}

export interface NativeIndexConfig {
  dimensions: number
  /** One of "l2" (default), "cosine", "innerProduct". */
  distance?: string
  maxNeighbors?: number
  buildSearchListSize?: number
  hasLabels?: boolean
}

export interface NativeItem {
  id: bigint
  vector: Float32Array
  labels?: Array<number>
}

/**
 * Partial per-query budget; unset fields keep the core defaults
 * (`QueryBudget::default()`). Byte-sized caps are `f64` because they can
 * exceed `u32`; the wrapper guarantees positive safe integers.
 */
export interface NativeQueryBudget {
  maxVisited?: number
  maxCandidates?: number
  maxReadBatch?: number
  maxRescore?: number
  maxFullVectorBytes?: number
  maxQueryBytes?: number
}

export interface NativeSearchOptions {
  limit: number
  searchListSize: number
  rescore?: boolean
  filterLabels?: Array<number>
  budget?: NativeQueryBudget
}

/**
 * Opens an existing index (strict-open semantics; never creates). When a
 * config is supplied it is asserted against the stored manifest config.
 */
export declare function openIndex(uri: string, config?: NativeIndexConfig | undefined | null): Promise<NativeIndex>

/**
 * Opens the index when it exists (asserting the supplied config against the
 * stored manifest config), otherwise creates it.
 */
export declare function openOrCreateIndex(uri: string, config: NativeIndexConfig): Promise<NativeIndex>
