/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeIndex {
  bulkBuild(items: Array<NativeItem>): Promise<unknown>
  search(vector: Float32Array, options: NativeSearchOptions): Promise<unknown>
  insert(item: NativeItem): Promise<unknown>
  delete(id: bigint): Promise<unknown>
  /**
   * Releases the native handle. Later calls on this instance fail with a
   * clear "index is closed" error, which the async wrapper surfaces as a
   * promise rejection.
   */
  close(): void
}

/** Creates an index for a storage-provider URI. Only `memory:` is supported. */
export declare function createIndex(uri: string, config: NativeIndexConfig): NativeIndex

export interface NativeHit {
  id: bigint
  distance: number
}

export interface NativeIndexConfig {
  dimensions: number
  /** One of "l2" (default), "cosine", "innerProduct". */
  distance?: string
  maxNeighbors?: number
  buildSearchListSize?: number
  hasLabels?: boolean
}

export interface NativeItem {
  id: bigint
  vector: Float32Array
  labels?: Array<number>
}

export interface NativeSearchOptions {
  limit: number
  searchListSize: number
  rescore?: boolean
}
